# Generated by Django 4.2.5 on 2023-10-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=255)),
                ('availability', models.BooleanField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('return_date', models.DateField()),
                ('return_time', models.TimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.vehicle')),
            ],
        ),
    ]
