# Generated by Django 4.2.5 on 2023-10-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='return_time',
        ),
    ]
