# Generated by Django 4.2.5 on 2023-11-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_remove_reservation_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='air',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='doors',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='img'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='kilometers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(default='Automatic', max_length=100),
        ),
    ]
